Repository FrankKair/polyglot-euler, pull requests merged in 2018-06, with the labels that each got.

#75 Clojure 005
  src/005/p005.cljc
Labels: clojure

#76 Clojure 006
  src/006/p006.cljc
Labels: clojure

#80 Crystal Ruby 021
  src/021/p021.cr
  src/021/p021.rb
Labels: crystal, ruby

#81 Perl 001 002
  CONTRIBUTING.md
  README.md
  src/001/p001.pl
  src/002/p002.pl
Labels: perl

#82 Lua 016
  src/016/p016.lua
Labels: lua

#77 Clojure 008
  src/008/p008.cljs
Labels: clojure

#84 Scala 006
  src/006/p006.scala
Labels: scala

#85 Scala 016
  src/004/p004.scala
  src/016/p016.scala
Labels: scala

#86 Futhark 001
  CONTRIBUTING.md
  README.md
  src/001/p001.fut
Labels: futhark

#87 Julia 001
  CONTRIBUTING.md
  README.md
  src/001/p001.jl
Labels: julia

#89 Clojure 007
  src/007/p007.cljc
Labels: clojure

#79 Clojure 009
  src/009/p009.clj
Labels: clojure
