Repository FrankKair/polyglot-euler, pull requests merged in 2018-09, with the labels that each got.

#101 Groovy 001
  CONTRIBUTING.md
  README.md
  src/001/p001.groovy
Labels: groovy

#102 Groovy 028
  src/028/p028.groovy
Labels: groovy

#104 CircleCI integration + Linguist
  .circleci/config.yml
Labels: enhancement

#106 Haskell 014 / Fix Rust 014
  src/014/p014.hs
  src/014/p014.rs
Labels: haskell, rust

#107 Haskell 015, 016 & 020
  src/015/p015.hs
  src/016/p016.hs
  src/018/README.md
  src/020/p020.hs
Labels: haskell

#108 Generating pie chart from linguist output
  .circleci/config.yml
  chart.sh
Labels: enhancement
