Repository FrankKair/polyglot-euler, pull requests merged in 2018-10, with the labels that each got.

#110 Clojure 058
  src/058/README.md
  src/058/p058.clj
Labels: clojure

#115 Red 022
  src/022/p022.red
Labels: Red

#113 Clojure 022
  src/022/p022.clj
Labels: clojure

#117 Fixing github-linguist
  .circleci/config.yml
  scripts/chart.sh
Labels: bug

#118 Replacing Bash with Shell
  README.md
Labels: enhancement

#119 Using github's colors on chart
  .circleci/config.yml
  scripts/chart.sh
Labels: enhancement
