Repository FrankKair/polyglot-euler, pull requests merged in 2018-05, with the labels that each got.

#56 Elixir 011, 013, 018, 022
  src/011/p011.exs
  src/013/p013.exs
  src/018/p018.exs
  src/022/p022.exs
Labels: elixir

#58 C++ 003
  src/003/p003.cpp
Labels: c++

#60 Scala 005
  src/005/p005.scala
Labels: scala

#63 Clojure 002
  src/002/p002.cljc
Labels: clojure

#62 Rust 036
  src/036/README.md
  src/036/p036.rs
Labels: rust

#59 C 104
  src/104/README.md
  src/104/p104.c
Labels: c

#65 Crystal Go Lua Swift 036
  src/036/p036.cr
  src/036/p036.go
  src/036/p036.lua
  src/036/p036.swift
Labels: crystal, go, lua, swift

#66 Clojure 004
  src/004/p004.cljc
Labels: clojure

#67 Removing redundant information
  src/018/p018.exs
  src/022/p022.exs
Labels: elixir

#68 Go Java 097
  src/097/p097.go
  src/097/p097.java
Labels: go, java

#64 Refactor: Rust 36 04
  src/004/p004.rs
  src/036/p036.rs
Labels: rust

#71 Go 016
  src/016/p016.go
Labels: go

#73 Python 025 028 036 097
  src/025/025.py
  src/028/028.py
  src/036/036.py
  src/097/097.py
Labels: python

#70 Crystal 048
  src/048/README.md
  src/048/p048.cr
Labels: crystal

#72 Elixir 017 019 029 030 034 048 055 089 097
  src/017/p017.exs
  src/019/p019.exs
  src/029/README.md
  src/029/p029.exs
  src/030/README.md
  src/030/p030.exs
  src/034/README.md
  src/034/p034.exs
  src/048/README.md
  src/048/p048.exs
  src/055/README.md
  src/055/p055.exs
  src/089/README.md
  src/089/p089.exs
  src/089/p089_roman.txt
  src/097/p097.exs
Labels: elixir
